<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit296a45b5f1853e472c7124de0de2d7be
{
    public static $prefixLengthsPsr4 = array (
        'E' => 
        array (
            'ExoProject\\Euclid\\' => 18,
            'ExoProject\\EuclidTest\\' => 22,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'ExoProject\\Euclid\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
        'ExoProject\\EuclidTest\\' => 
        array (
            0 => __DIR__ . '/../..' . '/test',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit296a45b5f1853e472c7124de0de2d7be::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit296a45b5f1853e472c7124de0de2d7be::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit296a45b5f1853e472c7124de0de2d7be::$classMap;

        }, null, ClassLoader::class);
    }
}
