<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'ExoProject\\Euclid\\' => array($baseDir . '/src'),
    'ExoProject\\EuclidTest\\' => array($baseDir . '/test'),
);
